server:
  port: 8082

spring:
  data:
    mongodb:
      host: localhost # mongodb的连接地址
      port: 27017 # mongodb的连接端口号
      database: test # mongodb的连接的数据库
      username: root
      password: root
      authentication-database: admin
